---
title: "Gallery"
---

```{r, echo=F, message=FALSE, warning=FALSE}
library(tidyverse)
acc = read_csv('data/accounts_analytical.csv')
acc = acc %>% 
  mutate(has_loan='Has Loan',
         `Credit Card`=!is.na(credit_cards),
         loan_day_after_open=acc$loan_date-acc$acct_creation_date)
acc[is.na(acc$loan_date), 'has_loan'] = 'No Loan'
# glimpse(acc)
```



```{r ,echo=F, message=FALSE, warning=FALSE}
tran = read_csv('data/transactions.csv')
tran %>% 
  group_by(account_id) %>% 
  summarize(average_balance = mean(balance)) %>% 
  left_join(acc, by=c('account_id' = 'account_id')) %>%
  
  ggplot(
      mapping = aes(
      x = average_balance,
      color= `Credit Card`
    )
  ) +
  geom_histogram() +
  labs(x="Average Balalce",
       y="Number of Account",
       title = 'Distribution of Account Type',
       legend = 'Credict Card') +
  
  facet_grid(~has_loan) +
  
  theme(
        strip.text = element_text(size = 10),
        legend.text = element_text( size = 10),
        legend.title = element_text(size = 10),
        plot.title =  element_text(size = 10)
        )
```

```{r,echo=F, message=FALSE, warning=FALSE}
library(tidyverse)
acc = read_csv('data/accounts_analytical.csv')
acc = acc %>% 
  mutate(has_loan='has loan',
         has_credit_card=!is.na(credit_cards),
         loan_day_after_open=acc$loan_date-acc$acct_creation_date)
```



```{r,echo=F, message=FALSE, warning=FALSE}
acc %>% 
  ggplot(aes(x = loan_amount))+
  geom_histogram() +
  labs(title = 'Distribution of loan amount',
       x = "Loan Amount",
       y = "Number of Accounts") 
```

The distribution of loan amount is nearly exponentially distributed. Few people has very high loan amount.

```{r,echo=F, message=FALSE, warning=FALSE}
library(tidyverse)
acc = read_csv('data/accounts_analytical.csv')
acc = acc %>% 
  mutate(has_loan='has loan',
         has_credit_card=!is.na(credit_cards),
         loan_day_after_open=acc$loan_date-acc$acct_creation_date,
         `Loan Default`=loan_default)
acc[is.na(acc$loan_date), 'has_loan'] = 'has no loan'
```

```{r,echo=F, message=FALSE, warning=FALSE}
acc %>% filter(!is.na(loan_day_after_open)) %>%
  ggplot(
    mapping = aes(x=loan_day_after_open, color=`Loan Default`)
  ) +
  geom_histogram()+
  labs(title = 'Distribution of loan amount',
       x = 'Loan Day After Account Opened',
       y = "Number of Accounst")
```

Statistical characteristics:

```{r, include=F, message=FALSE, warning=FALSE}
acc %>%
  summarise(mean = mean(loan_amount, na.rm=T),
            Median = median(loan_amount, na.rm=T),
            SD = sd(loan_amount, na.rm=T))
```


```{r, echo=F, message=FALSE, warning=FALSE}
library(tidyverse)
acc = read_csv('data/accounts_analytical.csv')
acc = acc %>% 
  mutate(has_loan='has loan',
         has_credit_card=!is.na(credit_cards),
         loan_day_after_open=acc$loan_date-acc$acct_creation_date)
acc[is.na(acc$loan_date), 'has_loan'] = 'has no loan'

tran = read_csv('data/transactions.csv')
# tran %>% 
#   group_by(account_id) %>% 
#   summarize(num_trans = n()) %>%
#   arrange(-num_trans)
```


The account with highest number of transactions is 8261.

<!-- ```{r, echo=F, fig.width=10, fig.height=8, message=FALSE, warning=FALSE} -->
<!-- tran %>% -->
<!--   filter(account_id==8261) %>% -->
<!--   arrange(date) %>% -->
<!--   ggplot(aes(x = date, -->
<!--              y = amount))+ -->
<!--   geom_line() + -->
<!--   facet_wrap( ~ type+ method+category,  scales = 'free') -->
<!-- ``` -->

<!-- Here is the time series plot. All bank transfers were periodic. Credit categories of interest credit and debit of method of cash had frequent transactions. -->


```{r,echo=F, message=F, warning=F}
# Download shape file from:
# https://bigdatateaching.blob.core.windows.net/public/tl_2019_us_county-1.zip
# and unzip in data folder
library(pacman)
p_load(char = c('tidyverse','sf','readxl','ggplot2','spData','ggpubr'))
countypres=read.csv('data/countypres_2000-2016.csv')
unemployment=read_excel('data/Unemployment.xls', skip=6) # get rid of the first 6 rows 
shape=st_read('data/tl_2019_us_county.shp', quiet=T)

# str(shape)
shape = shape %>% rename('FIPS'='GEOID')

unemp = unemployment[,c('FIPStxt','Unemployment_rate_2008','Unemployment_rate_2012','Unemployment_rate_2016')] %>% rename("FIPS"="FIPStxt")

library(stringr)
# str(countypres)
make_plots = function(s, p){
    county_df = countypres %>% filter((state==s) & (party==p))
    county_df['percentage'] = 100*county_df$candidatevotes / county_df$totalvotes
    county_df
    county_df['FIPS'] = lapply(county_df[,'FIPS'], as.character) %>% str_pad(5, pad='0')
    
    county_df = county_df %>% left_join(shape[,c('FIPS','geometry')], by='FIPS') %>% left_join(unemp, by='FIPS')
    
    
    make_pres_plot = function(year){
        g = county_df %>% filter(year==year) %>%
        ggplot() + geom_sf(aes(geometry=geometry,fill=percentage))+
        labs(title=paste0(as.character(year), ' Vote Proportion for ', p, ' in ', s))+
        xlab('Longitude')+
        ylab('Latitude')+
        theme(plot.title = element_text(color = "black", face="bold", size = 20),
              legend.title = element_text(color = "black",  size = 10),
              legend.text = element_text(color = "black", size = 10), 
              legend.position="right",
              strip.text = element_text(size = 10))
        g
    }
    
    all_pres_gs = lapply(c(2008,2012,2016), make_pres_plot)
    
    make_unem_plot = function(year){
        g = county_df %>% filter(year==year)  %>% rename('unemployment_rate'=paste0('Unemployment_rate_', as.character(year))) %>%
        ggplot() + geom_sf(aes(geometry=geometry,fill=unemployment_rate)) +
        scale_fill_viridis_c(name='unemployment rate (%)',option = "plasma", alpha = .8,direction = -1) +
        labs(title=paste0(as.character(year), ' Unemployment Rate of ', s))+
        xlab('Longitude')+
        ylab('Latitude')+
        theme(plot.title = element_text(color = "black", face="bold", size = 20),
              legend.title = element_text(color = "black",  size = 10),
              legend.text = element_text(color = "black", size = 10), 
              legend.position="right",
              strip.text = element_text(size = 10))
        g
    }
    all_unemployment_gs = lapply(c(2008,2012,2016), make_unem_plot)
    c(all_pres_gs, all_unemployment_gs)
}
```


```{r, echo=F, fig.width=20, fig.height=40, eval=T}
ca_gs = make_plots('California', 'democrat')
ggarrange(ca_gs[[1]],ca_gs[[4]],ca_gs[[2]],ca_gs[[5]],ca_gs[[3]],ca_gs[[6]], ncol=2, nrow=3, align='hv')
```


```{r, echo=F, fig.width=15,fig.height=20, eval=F, include=F}
tx_gs = make_plots('Texas', 'democrat')
ggarrange(tx_gs[[1]],tx_gs[[4]],tx_gs[[2]],tx_gs[[5]],tx_gs[[3]],tx_gs[[6]], ncol=2, nrow=3, align='hv')
```

```{r, echo=F, fig.width=15,fig.height=20, eval=F, include=F}
pa_gs = make_plots('Pennsylvania', 'democrat')
ggarrange(pa_gs[[1]],pa_gs[[4]],pa_gs[[2]],pa_gs[[5]],pa_gs[[3]],pa_gs[[6]], ncol=2, nrow=3, align='hv')
```



```{r, echo=F, fig.width=15,fig.height=20, echo=F, message=F, warning=F}

library(readxl)
library(tidyverse)
library(viridis)
library(patchwork)
library(hrbrthemes)
library(circlize)
library(chorddiag)  #devtools::install_github("mattflor/chorddiag")
df_raw = read_excel('data/State_to_State_Migrations_Table_2018.xls', skip=6)
# head(df_raw)
df_raw = df_raw %>% rename('dest'='...1')

# New York, Texas, District of Columbia, Virginia
clean_extract = function(df_raw, state){
  df_by_dest = df_raw[5:69, c('dest', state)]
  df_by_dest = df_by_dest %>% filter((!is.na(dest)) & (dest!='Current residence in'))
  df_by_dest['origin'] = state
  
  df_by_dest = df_by_dest[c(3,1,2)]
  colnames(df_by_dest) = c('from', 'to', 'value')
  df_by_dest['value'] = lapply(df_by_dest['value'], as.numeric)
  df_by_dest = df_by_dest %>% arrange(desc(value))
  df_by_dest[1:10,]
}
# clean_extract(df_raw, state='District of Columbia')

origins = c('New York', 'Texas', 'District of Columbia', 'Virginia')
all = NULL
for(state in origins){
  if(is.null(all)){
    all = clean_extract(df_raw, state)
  }else{
    all = rbind(all, clean_extract(df_raw, state))
  }
}


# color palette
set.seed(2333)
nsections = length(unique(all$to))
mycolor <- viridis(nsections, alpha = 1, begin = 0, end = 1, option = "D")
mycolor <- mycolor[sample(1:nsections)]
chordDiagram(all, 
             annotationTrack = "grid",
             grid.col = mycolor,
             preAllocateTracks = list(track.height = max(strwidth(unlist(dimnames(all))))),
             transparency = 0.25,
              directional = 1,
              direction.type = c("arrows", "diffHeight"), 
              diffHeight  = -0.04,
              annotationTrackHeight = c(0.05, 0.1),
              link.arr.type = "big.arrow", 
              link.sort = TRUE, 
              link.largest.ontop = TRUE)
# Add text
circos.track(track.index = 1,
             bg.border = NA,
             panel.fun = function(x, y) {
               
                  circos.text(CELL_META$xcenter, 
                              CELL_META$ylim[1], 
                              CELL_META$sector.index, 
                              facing = "clockwise", 
                              niceFacing = TRUE,  
                              adj = c(0, 0.8),
                              cex=1)
                   # Add graduation on axis
             }
             
             )
title(main=list("Top 10 Migration Destinations of New York, Texas, District of Columbia, Virginia", 
                cex = 2))
```





